---
abstract: 'Translates named variables to a hash list with corresponding keys'
author:
  - 'Glen Hinkle'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Eponymous-Hash
requires:
  PadWalker: 1.96
  Scalar::Util: 0
resources:
  repository: git://github.com/tempire/eponymous-hash.git
version: 0.02
